### ISSUE TITLE
pct exec

### ISSUE THREAD

**Issue by paul-hammant** [galdorork/tf-Proxmox#1]
https://medium.com/swlh/provision-proxmox-vms-with-terraform-quick-and-easy-5ad1975df1de is great, but would be even better if it included ...

```
pct exec 9000 -- apt install cloud-init -y
pct exec 9000 -- apt install bmon screen ntpdate vim locate locales-all iotop atop curl libpam-systemd python-pip python-dev ifenslave vlan mysql-client sysstat snmpd sudo lynx rsync nfs-common tcpdump strace darkstat qemu-guest-agent
pct exec 9000 -- shutdown -h now
```

**Comment by galdorork** [comment]
Thanks, glad you liked the article. It's my understanding that `pct` applies only for LXC containers though, the article is based on VMs.

I guess it could be done with a container template.

Also, I'm coming up with a few more articles and public repos as soon as I get some free time for it. Again, thanks for the support.

**Comment by paul-hammant** [comment]
Good thought - LXC containers only.  I try not to do Medium myself, but would be a fan or more articles from you :)
